// client/src/components/search-bar/customization/dietary-restrictions.tsx
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";

const DIETARY_OPTIONS = [
  { label: 'Halal', value: 'halal' },
  { label: 'Vegan', value: 'vegan' },
  { label: 'Vegetarion', value: 'vegetarian' },
  { label: 'Non-dairy', value: 'non-dairy' },
] as const;

export default function DietaryRestrictions() {
  return (
    <div className="grid grid-cols-2 gap-2">
      {DIETARY_OPTIONS.map(option => (        
        <div className="flex items-center gap-3" key={option.value}>
          <Checkbox
            id={option.value}
            defaultChecked={option.value === 'halal'}
          />
          <Label htmlFor={option.value}>{option.label}</Label>
        </div>
      ))}
    </div>
  );
}

// client/src/components/DietaryRestrictions.vue
<script setup>
import { ref } from 'vue';
import { Checkbox } from '@/components/ui/checkbox';

const checkboxes = ref([
  { id: 'halal', label: 'Halal', checked: true },
  { id: 'vegan', label: 'Vegan', checked: false },
  { id: 'vegetarian', label: 'Vegetarian', checked: false },
  { id: 'nondairy', label: 'Non-dairy', checked: false },
]);

const toggleCheckbox = (checkbox) => {
  checkbox.checked = !checkbox.checked;
};
</script>

<template>
  <div class="p-4 rounded-lg border bg-card text-card-foreground shadow-sm">
    <div class="font-bold mb-2">Dietary Restrictions</div>
    <div class="flex gap-10">
      <div 
        v-for="checkbox in checkboxes" 
        :key="checkbox.id" 
        class="flex items-center gap-2"
      >
        <Checkbox 
          :id="checkbox.id" 
          :checked="checkbox.checked" 
          @click="toggleCheckbox(checkbox)"
        />
        <label :for="checkbox.id">{{ checkbox.label }}</label>
      </div>
    </div>
  </div>
</template>
